"""Models package — exports all SQLAlchemy models."""
from __future__ import annotations

from app.models.base import Base, AsyncSessionLocal, engine, get_db, init_db, GUID
from app.models.identity import (
    User,
    BiometricProfile,
    UserDevice as IdentityDevice,
    UserDevice,
    Session,
    AuditLog,
    UserRole,
)
from app.models.soc import (
    Soc,
    Analyst,
    Device as SocDevice,
    Asset,
    Threat,
    Event,
    Alert,
    Incident,
    IncidentAlert,
    IncidentThreat,
    IncidentAsset,
    Investigation,
    Escalation,
    AnalystAction,
    Severity,
    AlertStatus,
    IncidentStatus,
    InvestigationStatus,
    EscalationStatus,
    AnalystRole,
    Shift,
    DeviceType,
    AssetType,
    Criticality,
)
from app.models.analytics import (
    Finding,
    RiskAssessment,
    Recommendation,
    FindingType,
    FindingSeverity,
    FindingStatus,
)

__all__ = [
    # Base
    "Base",
    "AsyncSessionLocal",
    "engine",
    "get_db",
    "init_db",
    # Identity
    "User",
    "BiometricProfile",
    "IdentityDevice",
    "Session",
    "AuditLog",
    "UserRole",
    # SOC
    "Soc",
    "Analyst",
    "SocDevice",
    "Asset",
    "Threat",
    "Event",
    "Alert",
    "Incident",
    "IncidentAlert",
    "IncidentThreat",
    "IncidentAsset",
    "Investigation",
    "Escalation",
    "AnalystAction",
    "Severity",
    "AlertStatus",
    "IncidentStatus",
    "InvestigationStatus",
    "EscalationStatus",
    "AnalystRole",
    "Shift",
    "DeviceType",
    "AssetType",
    "Criticality",
    # Analytics
    "Finding",
    "RiskAssessment",
    "Recommendation",
    "FindingType",
    "FindingSeverity",
    "FindingStatus",
]