'use client';

export * from './SocIcon';
export { default as SocIcon } from './SocIcon';

export * from './SocAccess';
export { default as SocAccess } from './SocAccess';
export * from './SocActivity';
export { default as SocActivity } from './SocActivity';
export * from './SocAlert';
export { default as SocAlert } from './SocAlert';
export * from './SocAnalytics';
export { default as SocAnalytics } from './SocAnalytics';
export * from './SocApi';
export { default as SocApi } from './SocApi';
export * from './SocBell';
export { default as SocBell } from './SocBell';
export * from './SocBookmark';
export { default as SocBookmark } from './SocBookmark';
export * from './SocBug';
export { default as SocBug } from './SocBug';
export * from './SocCalendar';
export { default as SocCalendar } from './SocCalendar';
export * from './SocCase';
export { default as SocCase } from './SocCase';
export * from './SocCertificate';
export { default as SocCertificate } from './SocCertificate';
export * from './SocChartLine';
export { default as SocChartLine } from './SocChartLine';
export * from './SocCheck';
export { default as SocCheck } from './SocCheck';
export * from './SocClock';
export { default as SocClock } from './SocClock';
export * from './SocClose';
export { default as SocClose } from './SocClose';
export * from './SocCloud';
export { default as SocCloud } from './SocCloud';
export * from './SocCloudAlert';
export { default as SocCloudAlert } from './SocCloudAlert';
export * from './SocCode';
export { default as SocCode } from './SocCode';
export * from './SocCopy';
export { default as SocCopy } from './SocCopy';
export * from './SocDashboard';
export { default as SocDashboard } from './SocDashboard';
export * from './SocDataSource';
export { default as SocDataSource } from './SocDataSource';
export * from './SocDatabase';
export { default as SocDatabase } from './SocDatabase';
export * from './SocDownload';
export { default as SocDownload } from './SocDownload';
export * from './SocEdit';
export { default as SocEdit } from './SocEdit';
export * from './SocEndpoint';
export { default as SocEndpoint } from './SocEndpoint';
export * from './SocEye';
export { default as SocEye } from './SocEye';
export * from './SocEyeOff';
export { default as SocEyeOff } from './SocEyeOff';
export * from './SocFile';
export { default as SocFile } from './SocFile';
export * from './SocFilter';
export { default as SocFilter } from './SocFilter';
export * from './SocFirewall';
export { default as SocFirewall } from './SocFirewall';
export * from './SocFolder';
export { default as SocFolder } from './SocFolder';
export * from './SocGlobe';
export { default as SocGlobe } from './SocGlobe';
export * from './SocHelp';
export { default as SocHelp } from './SocHelp';
export * from './SocHistory';
export { default as SocHistory } from './SocHistory';
export * from './SocHunting';
export { default as SocHunting } from './SocHunting';
export * from './SocIncident';
export { default as SocIncident } from './SocIncident';
export * from './SocInfo';
export { default as SocInfo } from './SocInfo';
export * from './SocIntegration';
export { default as SocIntegration } from './SocIntegration';
export * from './SocInvestigation';
export { default as SocInvestigation } from './SocInvestigation';
export * from './SocKey';
export { default as SocKey } from './SocKey';
export * from './SocLink';
export { default as SocLink } from './SocLink';
export * from './SocLock';
export { default as SocLock } from './SocLock';
export * from './SocLogin';
export { default as SocLogin } from './SocLogin';
export * from './SocLogout';
export { default as SocLogout } from './SocLogout';
export * from './SocLogs';
export { default as SocLogs } from './SocLogs';
export * from './SocMail';
export { default as SocMail } from './SocMail';
export * from './SocMalware';
export { default as SocMalware } from './SocMalware';
export * from './SocMessage';
export { default as SocMessage } from './SocMessage';
export * from './SocMinus';
export { default as SocMinus } from './SocMinus';
export * from './SocMonitoring';
export { default as SocMonitoring } from './SocMonitoring';
export * from './SocNetwork';
export { default as SocNetwork } from './SocNetwork';
export * from './SocPause';
export { default as SocPause } from './SocPause';
export * from './SocPin';
export { default as SocPin } from './SocPin';
export * from './SocPlay';
export { default as SocPlay } from './SocPlay';
export * from './SocPlaybook';
export { default as SocPlaybook } from './SocPlaybook';
export * from './SocPlus';
export { default as SocPlus } from './SocPlus';
export * from './SocPolicy';
export { default as SocPolicy } from './SocPolicy';
export * from './SocPulse';
export { default as SocPulse } from './SocPulse';
export * from './SocRefresh';
export { default as SocRefresh } from './SocRefresh';
export * from './SocReport';
export { default as SocReport } from './SocReport';
export * from './SocResponse';
export { default as SocResponse } from './SocResponse';
export * from './SocSearch';
export { default as SocSearch } from './SocSearch';
export * from './SocSearchUser';
export { default as SocSearchUser } from './SocSearchUser';
export * from './SocSend';
export { default as SocSend } from './SocSend';
export * from './SocServer';
export { default as SocServer } from './SocServer';
export * from './SocSettings';
export { default as SocSettings } from './SocSettings';
export * from './SocShield';
export { default as SocShield } from './SocShield';
export * from './SocShieldAlert';
export { default as SocShieldAlert } from './SocShieldAlert';
export * from './SocShieldCheck';
export { default as SocShieldCheck } from './SocShieldCheck';
export * from './SocSiem';
export { default as SocSiem } from './SocSiem';
export * from './SocSliders';
export { default as SocSliders } from './SocSliders';
export * from './SocSoar';
export { default as SocSoar } from './SocSoar';
export * from './SocSort';
export { default as SocSort } from './SocSort';
export * from './SocStar';
export { default as SocStar } from './SocStar';
export * from './SocTarget';
export { default as SocTarget } from './SocTarget';
export * from './SocTask';
export { default as SocTask } from './SocTask';
export * from './SocTeam';
export { default as SocTeam } from './SocTeam';
export * from './SocTerminal';
export { default as SocTerminal } from './SocTerminal';
export * from './SocThreat';
export { default as SocThreat } from './SocThreat';
export * from './SocThreatLevel';
export { default as SocThreatLevel } from './SocThreatLevel';
export * from './SocTimeline';
export { default as SocTimeline } from './SocTimeline';
export * from './SocTrash';
export { default as SocTrash } from './SocTrash';
export * from './SocUpload';
export { default as SocUpload } from './SocUpload';
export * from './SocUser';
export { default as SocUser } from './SocUser';
export * from './SocUsers';
export { default as SocUsers } from './SocUsers';
export * from './SocVirus';
export { default as SocVirus } from './SocVirus';
export * from './SocVulnerability';
export { default as SocVulnerability } from './SocVulnerability';
export * from './SocWifi';
export { default as SocWifi } from './SocWifi';
export * from './SocWorkflow';
export { default as SocWorkflow } from './SocWorkflow';
export * from './SocZap';
export { default as SocZap } from './SocZap';

// Legacy compatibility aliases
export { SocShieldCheck as SocShieldCheckLegacy } from './SocShieldCheck';
