import { Finding, SocHealthOverview, QuadrantScore, AnalystWorkloadItem, ThreatRecurrenceItem, AuditLogEntry } from '@/types';

export const SCENARIOS = [
  { id: 'investigation_gap', name: 'MĀYĀ-01 : Investigation Gap (Default)', desc: 'High-severity alerts closed without investigation records' },
  { id: 'analyst_overload', name: 'MĀYĀ-02 : Analyst Overload', desc: 'Workforce bottleneck and critical case concentration' },
  { id: 'negative_space', name: 'MĀYĀ-03 : Negative Space Gap (ABHĀVA)', desc: 'Missing mandatory forensic and containment actions' },
  { id: 'kpi_manipulation', name: 'MĀYĀ-04 : KPI Manipulation (VIKĀRA)', desc: 'Sub-60s rapid closures to artificially depress MTTR' },
  { id: 'recurring_threat', name: 'MĀYĀ-05 : Recurring Unresolved Threat', desc: 'Persistent attack pattern hitting same assets repeatedly' },
  { id: 'identity_anomaly', name: 'MĀYĀ-06 : Identity Anomaly (KAVACA)', desc: 'Session hijack & physical biometric mismatch' },
  { id: 'healthy', name: 'MĀYĀ-07 : Healthy Baseline SOC', desc: 'Nominal baseline operational metrics' },
];

export const MOCK_HEALTH_OVERVIEW: SocHealthOverview = {
  health_score: 78,
  status: 'DEGRADED',
  critical_findings: 7,
  active_anomalies: 23,
  execution_gaps: 14,
  negative_space: 6,
  threat_recurrences: 8,
  soc_scope: 'SOC-04',
  supervisor_name: 'A. Sharma',
  session_credential_state: 'ACTIVE',
};

export const MOCK_QUADRANT_SCORE: QuadrantScore = {
  detection_score: 92,
  investigation_score: 31,
  escalation_score: 48,
  response_score: 64,
  composite_grade: 'C-',
};

export const MOCK_FINDINGS: Finding[] = [
  {
    id: 'FND-EXEC-001',
    soc_scope: 'SOC-04',
    engine: 'VIVEKA',
    type: 'Execution Gap',
    severity: 'CRITICAL',
    status: 'OPEN',
    title: 'Investigation Gap in High-Severity Ransomware Detections',
    summary: '83 critical alerts were closed without corresponding investigation records or memory dumps.',
    confidence: 0.94,
    risk_score: 91,
    affected_scope: '83 alerts affected',
    detected_time: '2m ago',
    baseline_metric_name: 'Investigation Baseline',
    baseline_value: '85%',
    observed_value: '11%',
    deviation: '-74%',
    risk_factors: [
      { name: 'Investigation Gap', score: 31, description: '83 alerts closed without investigation steps' },
      { name: 'Escalation Anomaly', score: 24, description: 'High severity bypassed Tier 2/3 supervisor queue' },
      { name: 'Negative Space', score: 18, description: 'Missing memory dumps and host isolation logs' },
      { name: 'Closure Anomaly', score: 11, description: 'Average closure dwell time <45 seconds' },
      { name: 'Threat Recurrence', score: 7, description: 'Second instance targeting DC-PROD-01' },
    ],
    evidence_timeline: [
      { time: '10:31:02', event: 'Critical Alert: Ransomware Shadow Copy Deletion (vssadmin)', isAnomaly: false, type: 'ALERT' },
      { time: '10:31:18', event: 'Triage Assigned to Analyst A-01', isAnomaly: false, type: 'TRIAGE' },
      { time: '10:32:44', event: 'No Investigation (Forensic steps bypassed)', isAnomaly: true, type: 'GAP' },
      { time: '10:34:01', event: 'No Escalation (Tier 2 bypass)', isAnomaly: true, type: 'GAP' },
      { time: '10:34:22', event: 'Direct Closure as False Positive', isAnomaly: true, type: 'CLOSURE' },
    ],
    what: '83 critical alerts were closed without corresponding investigation records across Shift-Delta on DC-PROD-01.',
    why: 'Investigation baseline rate is 85%. Observed investigation rate was 11% (deviation: -74%). Average closure time was 42 seconds versus human baseline of 44 minutes.',
    when_detected: '2026-08-31 10:34:22 UTC',
    where_scope: 'Asset: DC-PROD-01 (10.14.2.1) | SOC-04 | Analyst: A-01',
    evidence: {
      total_alerts_affected: 83,
      soc_scope: 'SOC-04',
      analyst_id: 'A-01',
      ioc_hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      detection_engine: 'VIVEKA-v2.1',
      missing_actions: ['MEMORY_ACQUISITION', 'HOST_ISOLATION', 'PROCESS_INSPECTION'],
    },
    recommendation: 'Audit affected cases, revoke closure status on 83 alerts, and review the escalation workflow for SOC-04.',
    suggested_action: 'OPEN_SUPERVISORY_INVESTIGATION',
    affected_entities: [
      { type: 'Asset', id: 'DC-PROD-01', name: 'Primary Domain Controller' },
      { type: 'Analyst', id: 'A-01', name: 'Analyst A-01' },
      { type: 'SOC Scope', id: 'SOC-04' },
    ],
    related_incidents: ['INC-84920', 'INC-84918', 'INC-84905'],
    related_alerts: ['ALT-99201', 'ALT-99184', 'ALT-99150'],
    created_at: '2026-08-31T10:34:22Z',
  },
  {
    id: 'FND-VIK-002',
    soc_scope: 'SOC-04',
    engine: 'VIKĀRA',
    type: 'VIKĀRA',
    severity: 'HIGH',
    status: 'REVIEW',
    title: 'Abnormal Closure Pattern and MTTR Gaming',
    summary: 'Closure time shifted from 35-55 min baseline down to 3-5 min burst closures across 12 analysts.',
    confidence: 0.89,
    risk_score: 79,
    affected_scope: '12 analysts affected',
    detected_time: '8m ago',
    baseline_metric_name: 'Mean Closure MTTR',
    baseline_value: '35 - 55 min',
    observed_value: '3 - 5 min',
    deviation: '-88%',
    risk_factors: [
      { name: 'Rapid Resolution Burst', score: 35, description: '12 analysts closing incidents in <5m average' },
      { name: 'Investigation Evidence Drop', score: 26, description: 'Evidence collection dropped by 71%' },
      { name: 'Escalation Rate Drop', score: 18, description: 'Escalations dropped by 63%' },
    ],
    evidence_timeline: [
      { time: '10:20:00', event: 'Shift Handover Window Begins', isAnomaly: false },
      { time: '10:22:15', event: 'Burst Closure of 24 Incidents', isAnomaly: true },
      { time: '10:25:00', event: 'Isolation Forest Anomaly Score: -0.84', isAnomaly: true },
    ],
    what: '12 analysts exhibited rapid closure patterns prior to shift handover, resolving tickets without forensic query logs.',
    why: 'Normal baseline closure time is 35-55 min. Observed closure time was 3-5 min. Investigation evidence logged dropped by 71%, and escalation rate dropped by 63%.',
    when_detected: '2026-08-31 10:25:00 UTC',
    where_scope: 'SOC-04 | Queue: Tier 1 Triage | 12 Analysts',
    evidence: {
      affected_analysts_count: 12,
      mean_dwell_minutes: 3.8,
      baseline_dwell_minutes: 45.0,
      evidence_drop_pct: 71,
      escalation_drop_pct: 63,
    },
    recommendation: 'Reopen all 24 batch-dismissed alerts for supervisory peer review. Temporarily suspend single-click bulk resolution permission.',
    suggested_action: 'REOPEN_AND_AUDIT_ANALYSTS',
    affected_entities: [
      { type: 'SOC Scope', id: 'SOC-04' },
      { type: 'Queue', id: 'TIER-1-TRIAGE' },
    ],
    related_incidents: ['INC-83410', 'INC-83411'],
    related_alerts: ['ALT-97601', 'ALT-97602'],
    created_at: '2026-08-31T10:25:00Z',
  },
  {
    id: 'FND-ABH-003',
    soc_scope: 'SOC-02',
    engine: 'ABHĀVA',
    type: 'ABHĀVA',
    severity: 'HIGH',
    status: 'OPEN',
    title: 'Missing Mandatory Escalations on Cobalt Strike Telemetry',
    summary: '21 confirmed beacon detections closed without mandatory Tier 3 escalation or network isolation.',
    confidence: 0.91,
    risk_score: 84,
    affected_scope: '21 cases affected',
    detected_time: '12m ago',
    baseline_metric_name: 'Mandatory Escalation Rate',
    baseline_value: '100%',
    observed_value: '9.5%',
    deviation: '-90.5%',
    risk_factors: [
      { name: 'Missing Mandatory Escalation', score: 38, description: '21 lateral beacon cases unescalated' },
      { name: 'Omitted Host Isolation', score: 28, description: 'SOP-04 containment skipped' },
      { name: 'Multi-Host Threat Spread', score: 18, description: '4 connected subnet nodes at risk' },
    ],
    evidence_timeline: [
      { time: '10:10:00', event: 'Cobalt Strike Malleable C2 Detected on WORKSTATION-881', isAnomaly: false },
      { time: '10:12:30', event: 'Process Killed (Local Only)', isAnomaly: false },
      { time: '10:14:00', event: 'Missing Network Isolation Step', isAnomaly: true },
      { time: '10:15:33', event: 'Direct Closure without Tier 3 Escalation', isAnomaly: true },
    ],
    what: '21 confirmed Cobalt Strike beacon cases were marked resolved without mandatory network isolation or Tier 3 escalation.',
    why: 'SOP-04 mandates 100% escalation and network containment on confirmed C2 beacon telemetry. Expected escalations: 21, Observed: 2 (19 missing).',
    when_detected: '2026-08-31 10:15:33 UTC',
    where_scope: 'SOC-02 | Asset: WORKSTATION-881 (10.14.8.44)',
    evidence: {
      sop_id: 'SOP-04-CONTAINMENT',
      expected_escalations: 21,
      observed_escalations: 2,
      missing_escalations: 19,
      negative_space_score: 0.905,
    },
    recommendation: 'Issue immediate emergency network isolation on WORKSTATION-881 and escalate cases to Tier 3 Senior Incident Response.',
    suggested_action: 'ENFORCE_CONTAINMENT_AND_ESCALATE',
    affected_entities: [
      { type: 'SOC Scope', id: 'SOC-02' },
      { type: 'Asset', id: 'WORKSTATION-881' },
    ],
    related_incidents: ['INC-84801'],
    related_alerts: ['ALT-98711'],
    created_at: '2026-08-31T10:15:33Z',
  },
  {
    id: 'FND-PUN-004',
    soc_scope: 'SOC-04',
    engine: 'PUNARĀVṚTTI',
    type: 'PUNARĀVṚTTI',
    severity: 'HIGH',
    status: 'OPEN',
    title: 'Recurring Unresolved Threat: Kerberoasting on SQL DB Cluster',
    summary: 'Same threat actor signature detected 5 times across 14 days on SQL-SRV-02 with no root-cause credential rotation.',
    confidence: 0.87,
    risk_score: 82,
    affected_scope: '5 incidents / 1 asset',
    detected_time: '18m ago',
    baseline_metric_name: 'Recurrence Threshold',
    baseline_value: '0 Re-infections',
    observed_value: '5 Re-infections',
    deviation: '+500%',
    risk_factors: [
      { name: 'Recurrence Frequency', score: 36, description: '5 distinct incidents in 14 days' },
      { name: 'Remediation Failure', score: 30, description: 'Marked resolved without SPN rotation' },
      { name: 'Asset Criticality', score: 16, description: 'Core SQL Financial Records cluster' },
    ],
    evidence_timeline: [
      { time: 'Day 1', event: 'Incident INC-82100: Kerberoast RC4 detected on SQL-SRV-02' },
      { time: 'Day 4', event: 'Incident INC-82890: Ticket re-requested' },
      { time: 'Day 8', event: 'Incident INC-83410: Ticket re-requested' },
      { time: 'Day 11', event: 'Incident INC-84220: Ticket re-requested' },
      { time: 'Day 14', event: 'Incident INC-84901: Ticket re-requested (Current)' },
    ],
    what: 'Persistent threat actor targeting svc_sql_readonly via RC4 Kerberoasting without root-cause remediation.',
    why: 'Previous 4 incidents were closed as resolved without rotating Active Directory service account credentials or disabling RC4 encryption.',
    when_detected: '2026-08-31 09:45:00 UTC',
    where_scope: 'SOC-04 | Asset: SQL-SRV-02 (10.14.3.22) | Account: svc_sql_readonly',
    evidence: {
      threat_signature: 'T1558.003-KERBEROAST-RC4',
      first_seen: '2026-08-16T10:12:00Z',
      occurrence_count: 5,
      affected_asset: 'SQL-SRV-02',
      persisting_root_cause: 'Weak RC4 Kerberos encryption ticket unrotated',
    },
    recommendation: 'Rotate svc_sql_readonly password immediately, disable RC4 encryption support, and enforce AES-256 in Active Directory.',
    suggested_action: 'ROTATE_CREDENTIALS_AND_HARDEN',
    affected_entities: [
      { type: 'SOC Scope', id: 'SOC-04' },
      { type: 'Asset', id: 'SQL-SRV-02' },
      { type: 'Account', id: 'svc_sql_readonly' },
    ],
    related_incidents: ['INC-82100', 'INC-82890', 'INC-83410', 'INC-84220', 'INC-84901'],
    related_alerts: ['ALT-97601'],
    created_at: '2026-08-31T09:45:00Z',
  },
];

export const MOCK_WORKLOAD: AnalystWorkloadItem[] = [
  {
    analyst_id: 'A-01',
    name: 'Analyst A-01',
    role: 'Tier 1 Triage',
    critical_cases: 42,
    active_cases: 31,
    workload_level: 'HIGH',
    mean_closure_minutes: 4.8,
    investigation_rate: 0.11,
    is_bottleneck: true,
  },
  {
    analyst_id: 'A-02',
    name: 'Analyst A-02',
    role: 'Tier 2 Investigator',
    critical_cases: 17,
    active_cases: 12,
    workload_level: 'NORMAL',
    mean_closure_minutes: 42.1,
    investigation_rate: 0.88,
    is_bottleneck: false,
  },
  {
    analyst_id: 'A-03',
    name: 'Analyst A-03',
    role: 'Tier 2 Investigator',
    critical_cases: 14,
    active_cases: 10,
    workload_level: 'NORMAL',
    mean_closure_minutes: 38.5,
    investigation_rate: 0.92,
    is_bottleneck: false,
  },
  {
    analyst_id: 'A-04',
    name: 'Analyst A-04',
    role: 'Tier 1 Triage',
    critical_cases: 8,
    active_cases: 6,
    workload_level: 'LOW',
    mean_closure_minutes: 22.0,
    investigation_rate: 0.65,
    is_bottleneck: false,
  },
];

export const MOCK_THREAT_RECURRENCE: ThreatRecurrenceItem[] = [
  {
    threat_id: 'THR-APT-29',
    name: 'Kerberoasting & RC4 Exfiltration (T1558.003)',
    category: 'Credential Access',
    incident_chain: ['INC-82100', 'INC-82890', 'INC-83410', 'INC-84220', 'INC-84901'],
    first_seen: '2026-08-16 10:12:00 UTC',
    last_seen: '2026-08-31 09:45:00 UTC',
    affected_assets: ['SQL-SRV-02', 'DC-PROD-01', 'AUTH-NODE-01'],
    resolution_history: 'Closed 4 times as resolved without SPN rotation',
    recurrence_score: 92,
  },
  {
    threat_id: 'THR-MAL-14',
    name: 'Cobalt Strike Malleable C2 Beacon (T1071.004)',
    category: 'Command & Control',
    incident_chain: ['INC-84801', 'INC-84812'],
    first_seen: '2026-08-28 14:00:00 UTC',
    last_seen: '2026-08-31 10:15:33 UTC',
    affected_assets: ['WORKSTATION-881', 'DEV-HOST-12'],
    resolution_history: 'Active propagation across subnet 10.14.8.x',
    recurrence_score: 84,
  },
];

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'AUD-9904',
    timestamp: '22:14:01',
    user_id: 'SUP-17',
    user_role: 'SUPERVISOR',
    action: 'UPDATE_CASE',
    device_id: 'DEV-21',
    integrity_state: 'VERIFIED',
    target_id: 'CASE-2026-089',
    previous_hash: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
    current_hash: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
    details: 'Supervisor A. Sharma assigned Tier 3 forensic memory capture on DC-PROD-01',
  },
  {
    id: 'AUD-9903',
    timestamp: '22:12:44',
    user_id: 'SUP-17',
    user_role: 'SUPERVISOR',
    action: 'VIEW_EVIDENCE',
    device_id: 'DEV-21',
    integrity_state: 'VERIFIED',
    target_id: 'FND-EXEC-001',
    previous_hash: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
    current_hash: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
    details: 'Supervisor inspected 7-part explainability card & baseline deviation (-74%)',
  },
  {
    id: 'AUD-9902',
    timestamp: '22:11:18',
    user_id: 'SUP-17',
    user_role: 'SUPERVISOR',
    action: 'OPEN_FINDING',
    device_id: 'DEV-21',
    integrity_state: 'VERIFIED',
    target_id: 'FND-EXEC-001',
    previous_hash: 'ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d',
    current_hash: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
    details: 'Opened critical execution gap finding on SOC-04',
  },
  {
    id: 'AUD-9901',
    timestamp: '22:10:03',
    user_id: 'SUP-17',
    user_role: 'SUPERVISOR',
    action: 'LOGIN',
    device_id: 'DEV-21',
    integrity_state: 'VERIFIED',
    target_id: 'SESSION-KṢAṆA-771',
    previous_hash: '0000000000000000000000000000000000000000000000000000000000000000',
    current_hash: 'ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d',
    details: 'DARŚANA biometric facial verification + BANDHA device binding authenticated',
  },
];

export const MOCK_HISTORICAL_TRENDS = [
  { timestamp: '00:00', health_score: 82, critical_findings_count: 5, active_anomalies_count: 14 },
  { timestamp: '04:00', health_score: 79, critical_findings_count: 6, active_anomalies_count: 18 },
  { timestamp: '08:00', health_score: 71, critical_findings_count: 8, active_anomalies_count: 22 },
  { timestamp: '12:00', health_score: 65, critical_findings_count: 9, active_anomalies_count: 26 },
  { timestamp: '16:00', health_score: 74, critical_findings_count: 7, active_anomalies_count: 21 },
  { timestamp: '20:00', health_score: 78, critical_findings_count: 7, active_anomalies_count: 23 },
];


